const nome = 'Reynan';
const sobrenome = 'Paiva';
const idade = 19;
const peso = 65;
const altura = 1.80;
let imc = (peso / (altura * altura));
let anoNascimento = (2022 - idade);
console.log(nome, sobrenome, 'tem', idade, 'anos', ', pesa', peso, 'kg');
console.log('tem', altura, 'e seu imc é de', imc);
console.log(nome, sobrenome, 'nasceu no ano de', anoNascimento);